server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentacar
    username: sonar
    password: sonar
    driver-class-name: org.postgresql.Driver
    platform: org.hibernate.dialect.PostgreSQLDialect


pagina-inicial: home
      
