server:
  port: 8888
  
spring:
  datasource:
    url: jdbc:postgresql://172.17.0.4:5432/rentacar
    username: sonar
    password: sonar
    driver-class-name: org.postgresql.Driver
    platform: org.hibernate.dialect.PostgreSQLDialect


pagina-inicial: home
      
